#CRIAR UM PACOTE (EX107) E UM MÓDULO (MOEDA) QUE TENHA AS FUNÇÕES INCORPORADAS:
#AUMENTAR: AUMENTAR UMA QUANTIDADE % DE UM VALOR
#DIMINUIR: DIMINUIR UMA QUANTIDADE % DE UM VALOR
#DOBRO: DOBRAR UM VALOR
#METADE: DIVIDIR PELA METADE UM VALOR
#FAZER UM PROGRAMA QUE IMPORTE E USE ESTAS FUNÇÕES