#REESCREVER O EX 104
#INCLUIR A POSSIBILIDADE DA DIGITAÇÃO DE TIPO INVÁLIDO
#EXIBIR MENSAGEM DE ERRO E PEDIR PARA DIGITAR UM VALOR VÁLIDO
#PEDIR UM VALOR INTEIRO LEIAINT()
#PEDIR UM VALOR REAL LEIAFLOAT()