#CRIAR UM SISTEMA MODULARIZADO
#PERMITE CADASTRAR PESSOAS PELO NOME E IDADE EM UM ARQUIVO DE TEXTO SIMPLES
#O SISTEMA TER TRÊS OPÇÕES CADASTRAR UMA PESSOA NOVA OU LISTAR AS PESSOAS CADASTRADAS OU SAIR DO PROGRAMA